SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for recursive
-- ----------------------------
DROP TABLE IF EXISTS `recursive`;
CREATE TABLE `recursive`  (
  `ID` int NOT NULL,
  `PARENT_ID` int NULL DEFAULT NULL,
  `NAME` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of recursive
-- ----------------------------
INSERT INTO `recursive` VALUES (1, 0, 'Моторный отсек');
INSERT INTO `recursive` VALUES (2, 0, 'Система зажигания');
INSERT INTO `recursive` VALUES (3, 0, 'Система подачи топлива');
INSERT INTO `recursive` VALUES (4, 0, 'Ременный привод');
INSERT INTO `recursive` VALUES (5, 0, 'Система сцепления');
INSERT INTO `recursive` VALUES (6, 0, 'Коробка передач');
INSERT INTO `recursive` VALUES (7, 0, 'Главная передача');
INSERT INTO `recursive` VALUES (12, 0, 'Рулевое управление');
INSERT INTO `recursive` VALUES (13, 0, 'Система охлаждения');
INSERT INTO `recursive` VALUES (14, 0, 'Подготовка топливной смеси');
INSERT INTO `recursive` VALUES (15, 0, 'Система выпуска');
INSERT INTO `recursive` VALUES (16, 0, 'Электрооборудование автомобиля');
INSERT INTO `recursive` VALUES (17, 0, 'Трансмиссия');
INSERT INTO `recursive` VALUES (18, 0, 'Подвеска оси');
INSERT INTO `recursive` VALUES (19, 0, 'Колесо');
INSERT INTO `recursive` VALUES (20, 0, 'Тормозная система');
INSERT INTO `recursive` VALUES (21, 0, 'Воздушная система');
INSERT INTO `recursive` VALUES (22, 21, 'Кондиционер');
INSERT INTO `recursive` VALUES (23, 0, 'Система очистки окон');
INSERT INTO `recursive` VALUES (24, 0, 'Информационная система');
INSERT INTO `recursive` VALUES (25, 0, 'Салон');
INSERT INTO `recursive` VALUES (26, 0, 'Кузов');
INSERT INTO `recursive` VALUES (27, 0, 'Фильтр');
INSERT INTO `recursive` VALUES (28, 0, 'Разное');
INSERT INTO `recursive` VALUES (29, 27, 'Топливный фильтр');
INSERT INTO `recursive` VALUES (30, 27, 'Масляный фильтр');
INSERT INTO `recursive` VALUES (31, 27, 'Салонный фильтр');
INSERT INTO `recursive` VALUES (32, 27, 'Воздушный фильтр');
INSERT INTO `recursive` VALUES (33, 27, 'Фильтр КПП');
INSERT INTO `recursive` VALUES (34, 27, 'Фильтр АКПП');
INSERT INTO `recursive` VALUES (68, 27, 'Кожух воздушного фильтра');
INSERT INTO `recursive` VALUES (69, 27, 'Крышка масляного фильтра');
INSERT INTO `recursive` VALUES (70, 27, 'Кольцо корпуса масляного фильтра');
INSERT INTO `recursive` VALUES (71, 27, 'Кольцо масляного фильтра');
INSERT INTO `recursive` VALUES (72, 27, 'Корпус топливного фильтра');
INSERT INTO `recursive` VALUES (73, 27, 'Сажевый фильтр');
INSERT INTO `recursive` VALUES (74, 27, 'Фильтрующий элемент пыли');
INSERT INTO `recursive` VALUES (75, 2, 'Высоковольтные провода зажигания');
INSERT INTO `recursive` VALUES (76, 2, 'Зажигание');
INSERT INTO `recursive` VALUES (77, 2, 'Датчик детонации');
INSERT INTO `recursive` VALUES (78, 2, 'Датчик коленчатого вала');
INSERT INTO `recursive` VALUES (79, 2, 'Датчик работы цилиндра');
INSERT INTO `recursive` VALUES (80, 2, 'Катушка зажигания');
INSERT INTO `recursive` VALUES (81, 2, 'Прокладка для свечи зажигания');
INSERT INTO `recursive` VALUES (82, 2, 'Электронный узел зажигания и впрыска');
INSERT INTO `recursive` VALUES (83, 2, 'Замок зажигания');
INSERT INTO `recursive` VALUES (84, 2, 'Блок управления зажиганием');
INSERT INTO `recursive` VALUES (85, 2, 'Бегунок распределителя зажигания');
INSERT INTO `recursive` VALUES (86, 2, 'Датчик пропусков зажигания');
INSERT INTO `recursive` VALUES (87, 2, 'Уплотнительное кольцо крышки крепления катушки зажигания');
INSERT INTO `recursive` VALUES (88, 2, 'модуль зажигания');
INSERT INTO `recursive` VALUES (89, 2, 'Наконечник модуля зажигания');
INSERT INTO `recursive` VALUES (90, 2, 'Разъем модуля зажигания');
INSERT INTO `recursive` VALUES (91, 2, 'Ремкомплект распределителя системы зажигания');
INSERT INTO `recursive` VALUES (92, 2, 'Свеча зажигания');
INSERT INTO `recursive` VALUES (97, 2, 'Свечи накаливания');
INSERT INTO `recursive` VALUES (98, 26, 'Оборудование');
INSERT INTO `recursive` VALUES (99, 140, 'Бампер');
INSERT INTO `recursive` VALUES (107, 140, 'Дверь багажника');
INSERT INTO `recursive` VALUES (110, 140, 'Дверь');
INSERT INTO `recursive` VALUES (113, 140, 'Капот');
INSERT INTO `recursive` VALUES (115, 140, 'Крыло');
INSERT INTO `recursive` VALUES (116, 140, 'Накладка бампера');
INSERT INTO `recursive` VALUES (118, 140, 'Накладка на порог');
INSERT INTO `recursive` VALUES (120, 140, 'Боковая подушка безопасности');
INSERT INTO `recursive` VALUES (121, 140, 'Стекло двери');
INSERT INTO `recursive` VALUES (122, 140, 'Стекло лобовое');
INSERT INTO `recursive` VALUES (123, 98, 'Дефлектор капота');
INSERT INTO `recursive` VALUES (125, 98, 'Актуатор в дверь');
INSERT INTO `recursive` VALUES (126, 98, 'Амортизатор капота');
INSERT INTO `recursive` VALUES (127, 98, 'Электродвигатель очистителя заднего стекла');
INSERT INTO `recursive` VALUES (128, 98, 'Электродвигатель очистителя лобового стекла');
INSERT INTO `recursive` VALUES (129, 98, 'Подкрылок');
INSERT INTO `recursive` VALUES (130, 98, 'Замок багажника');
INSERT INTO `recursive` VALUES (133, 98, 'Замок капота');
INSERT INTO `recursive` VALUES (135, 98, 'Защита картера');
INSERT INTO `recursive` VALUES (136, 98, 'Зеркало электрическое');
INSERT INTO `recursive` VALUES (137, 98, 'Трос привода открытия капота');
INSERT INTO `recursive` VALUES (138, 98, 'Щетка очистителя лобового стекла');
INSERT INTO `recursive` VALUES (139, 98, 'Щетка очистителя заднего стекла');
INSERT INTO `recursive` VALUES (140, 26, 'Кузовные работы');
INSERT INTO `recursive` VALUES (141, 21, 'Вентиляция');
INSERT INTO `recursive` VALUES (142, 22, 'Радиатор кондиционера');
INSERT INTO `recursive` VALUES (143, 22, 'Кондиционер');
INSERT INTO `recursive` VALUES (144, 22, 'Муфта');
INSERT INTO `recursive` VALUES (145, 22, 'Трубка кондиционера');
INSERT INTO `recursive` VALUES (146, 22, 'Шланг кондиционера');
INSERT INTO `recursive` VALUES (149, 22, 'Компрессор кондиционера');
INSERT INTO `recursive` VALUES (150, 22, 'Топливная форсунка');
INSERT INTO `recursive` VALUES (151, 22, 'Датчик включения вентилятора');
INSERT INTO `recursive` VALUES (152, 22, 'Муфта вентилятора системы охлаждения');
INSERT INTO `recursive` VALUES (153, 22, 'Электродвигатель вентилятора системы охлаждения');
INSERT INTO `recursive` VALUES (154, 22, 'Герметичность системы кондиционера');
INSERT INTO `recursive` VALUES (155, 22, 'Расширительный клапан кондиционера');
INSERT INTO `recursive` VALUES (156, 22, 'Электродвигатель вентилятора испарителя');
INSERT INTO `recursive` VALUES (157, 22, 'Панель управления кондиционером');
INSERT INTO `recursive` VALUES (158, 22, 'Клапан регулировки рабочего объема компрессора кондиционера');
INSERT INTO `recursive` VALUES (159, 22, 'Хладагент системы кондиционирования');
INSERT INTO `recursive` VALUES (160, 22, 'Масло в системе кондиционирования');
INSERT INTO `recursive` VALUES (161, 22, 'Количество масла системы кондиционирования');
INSERT INTO `recursive` VALUES (162, 22, 'Количество хладагента системы кондиционирования');
INSERT INTO `recursive` VALUES (163, 22, 'Вязкость масла системы кондиционирования');
INSERT INTO `recursive` VALUES (164, 22, 'Количество сервисных разъемов кондиционера');
INSERT INTO `recursive` VALUES (165, 22, 'Подшипник компрессора кондиционера');
INSERT INTO `recursive` VALUES (166, 22, 'Электродвигатель вентилятора отопителя');
INSERT INTO `recursive` VALUES (167, 22, 'Вентилятор отопителя');
INSERT INTO `recursive` VALUES (168, 22, 'Линия от компрессора до конденсатора');
INSERT INTO `recursive` VALUES (169, 22, 'Конденсатор');
INSERT INTO `recursive` VALUES (170, 22, 'Реле кондиционера');
INSERT INTO `recursive` VALUES (171, 22, 'Реле электродвигателя вентилятора системы охлаждения');
INSERT INTO `recursive` VALUES (172, 141, 'Реле двигателя воздуходувки');
INSERT INTO `recursive` VALUES (173, 141, 'Обогреватель в сборе');
INSERT INTO `recursive` VALUES (174, 141, 'Радиатор обогревателя');
INSERT INTO `recursive` VALUES (176, 141, 'Рычаги управления радиатором');
INSERT INTO `recursive` VALUES (177, 141, 'Шланг обогревателя к двигателю');
INSERT INTO `recursive` VALUES (178, 141, 'Шланг обогревателя от двигателя');
INSERT INTO `recursive` VALUES (179, 141, 'Топливная форсунка');
INSERT INTO `recursive` VALUES (180, 141, 'Датчик включения вентилятора');
INSERT INTO `recursive` VALUES (181, 141, 'Электродвигатель вентилятора отопителя');
INSERT INTO `recursive` VALUES (182, 141, 'Вентилятор отопителя');
INSERT INTO `recursive` VALUES (183, 141, 'Кнопка обогрева стекла');
INSERT INTO `recursive` VALUES (184, 141, 'Обогрев стекла');
INSERT INTO `recursive` VALUES (185, 141, 'Обогрев зеркала заднего вида на двери');
INSERT INTO `recursive` VALUES (186, 141, 'Реле обогрева лобового стекла');
INSERT INTO `recursive` VALUES (187, 141, 'Реле обогрева заднего стекла');
INSERT INTO `recursive` VALUES (189, 3, 'Система подачи топлива');
INSERT INTO `recursive` VALUES (190, 189, 'Насос топливный');
INSERT INTO `recursive` VALUES (191, 189, 'Клапан отсечки топлива');
INSERT INTO `recursive` VALUES (192, 189, 'Топливный бак');
INSERT INTO `recursive` VALUES (193, 189, 'Топливная рампа');
INSERT INTO `recursive` VALUES (194, 189, 'Топливопровод');
INSERT INTO `recursive` VALUES (195, 189, 'Давление топлива');
INSERT INTO `recursive` VALUES (196, 3, 'Система впрыска топлива');
INSERT INTO `recursive` VALUES (197, 196, 'Датчик расхода воздуха');
INSERT INTO `recursive` VALUES (198, 196, 'Дроссельная заслонка');
INSERT INTO `recursive` VALUES (199, 196, 'Корпус дроссельной заслонки');
INSERT INTO `recursive` VALUES (200, 196, 'Топливная форсунка');
INSERT INTO `recursive` VALUES (201, 196, 'Регулятор давления топлива');
INSERT INTO `recursive` VALUES (202, 196, 'Датчик скорости');
INSERT INTO `recursive` VALUES (203, 196, 'Датчик температуры охлаждающей жидкости');
INSERT INTO `recursive` VALUES (204, 196, 'Датчик холостого хода');
INSERT INTO `recursive` VALUES (205, 196, 'Клапан управления холостого хода');
INSERT INTO `recursive` VALUES (206, 196, 'ТНВД');
INSERT INTO `recursive` VALUES (207, 196, 'трубка форсунки');
INSERT INTO `recursive` VALUES (209, 196, 'Электромагнитный клапан оборотов прогрева');
INSERT INTO `recursive` VALUES (210, 196, 'Электронный узел управления');
INSERT INTO `recursive` VALUES (211, 196, 'Воздушный тракт');
INSERT INTO `recursive` VALUES (212, 196, 'Свечи накаливания');
INSERT INTO `recursive` VALUES (213, 3, 'Турбонаддув');
INSERT INTO `recursive` VALUES (214, 213, 'Датчик давления турбонаддува');
INSERT INTO `recursive` VALUES (215, 213, 'Радиатор охлаждения наддувочного воздуха');
INSERT INTO `recursive` VALUES (216, 213, 'Турбокомпрессор');
INSERT INTO `recursive` VALUES (217, 213, 'Промежуточный охладитель наддувочного воздуха');
INSERT INTO `recursive` VALUES (218, 196, 'Форсунка впрыска мочевины');
INSERT INTO `recursive` VALUES (219, 196, 'Электронный узел зажигания и впрыска');
INSERT INTO `recursive` VALUES (220, 3, 'Управление газом');
INSERT INTO `recursive` VALUES (221, 220, 'Дроссельная заслонка');
INSERT INTO `recursive` VALUES (222, 220, 'Трос газа');
INSERT INTO `recursive` VALUES (224, 13, 'Система охлаждения');
INSERT INTO `recursive` VALUES (225, 13, 'Вентилятор системы охлаждения');
INSERT INTO `recursive` VALUES (226, 13, 'Расширительный бачок');
INSERT INTO `recursive` VALUES (227, 13, 'Корпус термостата');
INSERT INTO `recursive` VALUES (228, 13, 'Термостат');
INSERT INTO `recursive` VALUES (229, 13, 'Бачок системы охлаждения');
INSERT INTO `recursive` VALUES (230, 13, 'Вязкостная муфта');
INSERT INTO `recursive` VALUES (231, 13, 'Кран отопителя');
INSERT INTO `recursive` VALUES (232, 13, 'Патрубок');
INSERT INTO `recursive` VALUES (233, 13, 'Помпа');
INSERT INTO `recursive` VALUES (234, 13, 'Радиатор');
INSERT INTO `recursive` VALUES (235, 13, 'Радиатор обогревателя');
INSERT INTO `recursive` VALUES (236, 13, 'Тройник системы охлаждения');
INSERT INTO `recursive` VALUES (237, 13, 'Трубка системы охлаждения');
INSERT INTO `recursive` VALUES (238, 13, 'Шланг системы охлаждения');
INSERT INTO `recursive` VALUES (239, 13, 'Воздух');
INSERT INTO `recursive` VALUES (240, 13, 'Шкив водяного насоса');
INSERT INTO `recursive` VALUES (241, 5, 'Сцепление');
INSERT INTO `recursive` VALUES (242, 241, 'Узел сцепления и маховик');
INSERT INTO `recursive` VALUES (243, 242, 'Сцепление');
INSERT INTO `recursive` VALUES (246, 242, 'Выжимной подшипник');
INSERT INTO `recursive` VALUES (247, 242, 'Маховик');
INSERT INTO `recursive` VALUES (248, 242, 'Вилки сцепления');
INSERT INTO `recursive` VALUES (249, 242, 'Главный цилиндр');
INSERT INTO `recursive` VALUES (250, 242, 'Рабочий цилиндр');
INSERT INTO `recursive` VALUES (251, 242, 'Трос сцепления');
INSERT INTO `recursive` VALUES (252, 242, 'Крышка и выжимной подшипник нажимного диска');
INSERT INTO `recursive` VALUES (253, 242, 'Подшипник первичного вала КПП');
INSERT INTO `recursive` VALUES (255, 6, 'Автоматическая коробка переключения передач');
INSERT INTO `recursive` VALUES (256, 6, 'Механическая коробка переключения передач');
INSERT INTO `recursive` VALUES (258, 255, 'Роботизированная КПП');
INSERT INTO `recursive` VALUES (260, 255, 'Датчик АКПП');
INSERT INTO `recursive` VALUES (261, 255, 'Прокладка АКПП');
INSERT INTO `recursive` VALUES (262, 255, 'Радиатор вариатора');
INSERT INTO `recursive` VALUES (263, 255, 'Сальник АКПП к карданному валу');
INSERT INTO `recursive` VALUES (264, 255, 'Трубки охлаждения АКПП');
INSERT INTO `recursive` VALUES (265, 255, 'Поддон АКПП');
INSERT INTO `recursive` VALUES (266, 255, 'Селектор АКПП');
INSERT INTO `recursive` VALUES (267, 255, 'Трансмиссионное масло АКПП');
INSERT INTO `recursive` VALUES (268, 255, 'Гидротрансформатор и ведущий диск');
INSERT INTO `recursive` VALUES (269, 268, 'Муфта привода');
INSERT INTO `recursive` VALUES (270, 268, 'Трансформатор');
INSERT INTO `recursive` VALUES (271, 268, 'Центральное уплотнение трансформатора');
INSERT INTO `recursive` VALUES (272, 256, 'Коробка переключения передач и корпус');
INSERT INTO `recursive` VALUES (273, 272, 'Коробка передач');
INSERT INTO `recursive` VALUES (274, 272, 'Обойма шаровой опоры рычага кпп');
INSERT INTO `recursive` VALUES (275, 272, 'Опора КПП');
INSERT INTO `recursive` VALUES (276, 272, 'Опора раздатки');
INSERT INTO `recursive` VALUES (277, 272, 'Опора рычага кпп');
INSERT INTO `recursive` VALUES (278, 272, 'Трос управления МКПП');
INSERT INTO `recursive` VALUES (279, 272, 'Поддон КПП');
INSERT INTO `recursive` VALUES (280, 256, 'Механизм переключения передач');
INSERT INTO `recursive` VALUES (281, 280, 'Механическая коробка переключения передач');
INSERT INTO `recursive` VALUES (283, 280, 'Кулиса в сборе');
INSERT INTO `recursive` VALUES (286, 12, 'Геометрия рулевого механизма');
INSERT INTO `recursive` VALUES (287, 12, 'Гидроусилитель');
INSERT INTO `recursive` VALUES (288, 12, 'Рулевая колонка');
INSERT INTO `recursive` VALUES (289, 12, 'Рулевой механизм');
INSERT INTO `recursive` VALUES (290, 286, 'Колесо');
INSERT INTO `recursive` VALUES (293, 287, 'Гидравлический усилитель руля');
INSERT INTO `recursive` VALUES (294, 287, 'Бачок ГУРа');
INSERT INTO `recursive` VALUES (295, 287, 'Ремень привода ГУР');
INSERT INTO `recursive` VALUES (296, 287, 'Трубка ГУР');
INSERT INTO `recursive` VALUES (297, 287, 'Шкив ГУР');
INSERT INTO `recursive` VALUES (298, 287, 'Шланг ГУР');
INSERT INTO `recursive` VALUES (299, 287, 'Радиатор ГУР');
INSERT INTO `recursive` VALUES (300, 287, 'Насос ГУР');
INSERT INTO `recursive` VALUES (301, 288, 'Рулевая колонка');
INSERT INTO `recursive` VALUES (302, 288, 'Рулевое колесо');
INSERT INTO `recursive` VALUES (303, 288, 'Кожух рулевой колонки');
INSERT INTO `recursive` VALUES (304, 289, 'Пыльник рулевой рейки');
INSERT INTO `recursive` VALUES (305, 289, 'Рулевой механизм');
INSERT INTO `recursive` VALUES (306, 289, 'Наконечник рулевой тяги');
INSERT INTO `recursive` VALUES (307, 289, 'Рулевая тяга');
INSERT INTO `recursive` VALUES (308, 289, 'Крестовина рулевого кардана');
INSERT INTO `recursive` VALUES (309, 289, 'Маятниковый рычаг');
INSERT INTO `recursive` VALUES (310, 289, 'Рулевой вал');
INSERT INTO `recursive` VALUES (311, 289, 'Рулевой кардан');
INSERT INTO `recursive` VALUES (312, 289, 'Рулевая рейка');
INSERT INTO `recursive` VALUES (313, 289, 'Рулевая трапеция');
INSERT INTO `recursive` VALUES (315, 289, 'Шарнир наконечника поперечной рулевой тяги');
INSERT INTO `recursive` VALUES (316, 20, 'ABS');
INSERT INTO `recursive` VALUES (317, 20, 'Гидросистема привода');
INSERT INTO `recursive` VALUES (318, 20, 'Педаль и усилитель');
INSERT INTO `recursive` VALUES (319, 20, 'Ручной тормоз');
INSERT INTO `recursive` VALUES (320, 20, 'Реактивная тяга');
INSERT INTO `recursive` VALUES (321, 316, 'Датчик ABS на колесе');
INSERT INTO `recursive` VALUES (322, 316, 'Блок управления ABS');
INSERT INTO `recursive` VALUES (323, 316, 'Привод');
INSERT INTO `recursive` VALUES (325, 316, 'Электронный узел управления ABS');
INSERT INTO `recursive` VALUES (326, 317, 'Главный тормозной цилиндр');
INSERT INTO `recursive` VALUES (327, 317, 'Направляющие суппорта');
INSERT INTO `recursive` VALUES (328, 317, 'Тормозной цилиндр');
INSERT INTO `recursive` VALUES (329, 317, 'Скоба суппорта');
INSERT INTO `recursive` VALUES (330, 317, 'Суппорт');
INSERT INTO `recursive` VALUES (331, 317, 'Тормозная трубка');
INSERT INTO `recursive` VALUES (333, 317, 'Тормозная система');
INSERT INTO `recursive` VALUES (335, 317, 'Тормозной бачок');
INSERT INTO `recursive` VALUES (336, 317, 'Тормозной шланг');
INSERT INTO `recursive` VALUES (337, 318, 'Вакуумный шланг к коллектору');
INSERT INTO `recursive` VALUES (338, 318, 'Датчик педали тормоза');
INSERT INTO `recursive` VALUES (339, 318, 'Вакуумный насос');
INSERT INTO `recursive` VALUES (340, 318, 'Вакуумный тормозной усилитель');
INSERT INTO `recursive` VALUES (341, 318, 'Обратный клапан усилителя тормозов');
INSERT INTO `recursive` VALUES (342, 319, 'Колодка ручного тормоза');
INSERT INTO `recursive` VALUES (343, 319, 'Трос ручного тормоза');
INSERT INTO `recursive` VALUES (344, 319, 'Рычаг');
INSERT INTO `recursive` VALUES (345, 319, 'Механический ручной тормоз ');
INSERT INTO `recursive` VALUES (346, 319, 'Электрический ручной тормоз');
INSERT INTO `recursive` VALUES (347, 320, 'Тормозной диск');
INSERT INTO `recursive` VALUES (349, 320, 'Тормозной барабан');
INSERT INTO `recursive` VALUES (350, 320, 'Тормозные колодки');
INSERT INTO `recursive` VALUES (352, 320, 'Накладки тормозов');
INSERT INTO `recursive` VALUES (354, 320, 'Опорный диск тормоза');
INSERT INTO `recursive` VALUES (356, 1, 'Головка блока цилиндров');
INSERT INTO `recursive` VALUES (357, 1, 'Коленчатый вал и поршни');
INSERT INTO `recursive` VALUES (358, 1, 'Двигатель');
INSERT INTO `recursive` VALUES (359, 1, 'Распределительный вал и механизм привода');
INSERT INTO `recursive` VALUES (360, 1, 'Система смазки');
INSERT INTO `recursive` VALUES (361, 356, 'Головка блока цилиндров');
INSERT INTO `recursive` VALUES (363, 356, 'Клапан двигателя');
INSERT INTO `recursive` VALUES (365, 356, 'Гидрокомпенсатор');
INSERT INTO `recursive` VALUES (366, 356, 'Прокладки клапанной крышки');
INSERT INTO `recursive` VALUES (367, 356, 'Уплотнение стебля клапанов');
INSERT INTO `recursive` VALUES (368, 356, 'Клапан ЕГР');
INSERT INTO `recursive` VALUES (370, 356, 'Электромагнитный клапан');
INSERT INTO `recursive` VALUES (371, 357, 'Коленчатый вал');
INSERT INTO `recursive` VALUES (372, 357, 'Поршневое кольцо');
INSERT INTO `recursive` VALUES (373, 357, 'Поршень');
INSERT INTO `recursive` VALUES (374, 357, 'Сальник коленчатого вала');
INSERT INTO `recursive` VALUES (376, 357, 'Коренные подшипники коленчатого вала');
INSERT INTO `recursive` VALUES (377, 357, 'Шкив коленчатого вала');
INSERT INTO `recursive` VALUES (379, 358, 'Двигатель');
INSERT INTO `recursive` VALUES (386, 358, 'Блок цилиндров');
INSERT INTO `recursive` VALUES (387, 358, 'Впускной коллектор');
INSERT INTO `recursive` VALUES (388, 358, 'Клапан картерных газов');
INSERT INTO `recursive` VALUES (389, 358, 'Крышка');
INSERT INTO `recursive` VALUES (390, 358, 'Прокладка теплообменника');
INSERT INTO `recursive` VALUES (391, 358, 'Трубки картерных газов');
INSERT INTO `recursive` VALUES (392, 358, 'Турбина');
INSERT INTO `recursive` VALUES (393, 358, 'Опора двигателя');
INSERT INTO `recursive` VALUES (394, 358, 'Короткий блок двигателя');
INSERT INTO `recursive` VALUES (395, 358, 'Прокладка впускного коллектора');
INSERT INTO `recursive` VALUES (396, 359, 'Натяжитель цепи привода газораспределительного механизма');
INSERT INTO `recursive` VALUES (397, 359, 'Распределительный вал');
INSERT INTO `recursive` VALUES (398, 359, 'Ремень привода газораспределительного механизма');
INSERT INTO `recursive` VALUES (399, 359, 'Сальник распределительного вала');
INSERT INTO `recursive` VALUES (400, 359, 'Цепь газораспределительного механизма');
INSERT INTO `recursive` VALUES (401, 359, 'Толкатели распределительного вала');
INSERT INTO `recursive` VALUES (403, 359, 'Пружинка натяжного ролика');
INSERT INTO `recursive` VALUES (404, 359, 'Ролик натяжителя ремня вспомогательных агрегатов');
INSERT INTO `recursive` VALUES (405, 359, 'Натяжной ролик приводного ремня');
INSERT INTO `recursive` VALUES (406, 359, 'Промежуточный ролик');
INSERT INTO `recursive` VALUES (407, 359, 'Ролик ремня газораспределительного механизма');
INSERT INTO `recursive` VALUES (408, 359, 'Шестерня газораспределительного механизма');
INSERT INTO `recursive` VALUES (410, 360, 'Масляный насос');
INSERT INTO `recursive` VALUES (411, 360, 'Масляный поддон');
INSERT INTO `recursive` VALUES (412, 360, 'Прокладка масляного поддона');
INSERT INTO `recursive` VALUES (413, 360, 'Цепь маслянного насоса');
INSERT INTO `recursive` VALUES (414, 360, 'Давление масла');
INSERT INTO `recursive` VALUES (415, 360, 'Масляный радиатор охлаждения');
INSERT INTO `recursive` VALUES (416, 18, 'Передняя подвеска');
INSERT INTO `recursive` VALUES (417, 18, 'Задняя подвеска');
INSERT INTO `recursive` VALUES (418, 18, 'Подвеска');
INSERT INTO `recursive` VALUES (419, 417, 'Втулка стабилизатора');
INSERT INTO `recursive` VALUES (420, 417, 'Опора амортизатора');
INSERT INTO `recursive` VALUES (421, 417, 'Подвеска');
INSERT INTO `recursive` VALUES (422, 417, 'Рычаг подвески');
INSERT INTO `recursive` VALUES (423, 417, 'Стабилизатор');
INSERT INTO `recursive` VALUES (424, 417, 'Балка');
INSERT INTO `recursive` VALUES (425, 417, 'Пружина');
INSERT INTO `recursive` VALUES (427, 417, 'Пыльник амортизатора');
INSERT INTO `recursive` VALUES (428, 417, 'Стойка стабилизатора');
INSERT INTO `recursive` VALUES (430, 417, 'Толкающий рычаг подвески');
INSERT INTO `recursive` VALUES (431, 417, 'Тяга стабилизатора подвестки');
INSERT INTO `recursive` VALUES (432, 417, 'Демферы пыльников амортизатора');
INSERT INTO `recursive` VALUES (433, 417, 'Проставки амортизатора');
INSERT INTO `recursive` VALUES (434, 417, 'Амортизатор');
INSERT INTO `recursive` VALUES (435, 417, 'Сайлентблок балки');
INSERT INTO `recursive` VALUES (436, 416, 'Подвеска');
INSERT INTO `recursive` VALUES (437, 416, 'Втулка стабилизатора');
INSERT INTO `recursive` VALUES (438, 416, 'Рычаг подвески');
INSERT INTO `recursive` VALUES (439, 416, 'Опора стойки подвески');
INSERT INTO `recursive` VALUES (440, 416, 'Втулка рычага подвески');
INSERT INTO `recursive` VALUES (442, 416, 'Опора амортизатора');
INSERT INTO `recursive` VALUES (443, 416, 'Амортизатор');
INSERT INTO `recursive` VALUES (444, 416, 'Стабилизатор');
INSERT INTO `recursive` VALUES (445, 416, 'Балка');
INSERT INTO `recursive` VALUES (446, 416, 'Подшипник опоры амортизатора');
INSERT INTO `recursive` VALUES (447, 416, 'Пружина');
INSERT INTO `recursive` VALUES (448, 416, 'Поворотный кулак');
INSERT INTO `recursive` VALUES (449, 416, 'Поперечная тяга');
INSERT INTO `recursive` VALUES (450, 416, 'Реактивная тяга');
INSERT INTO `recursive` VALUES (451, 416, 'Опора подрамника подвески');
INSERT INTO `recursive` VALUES (453, 416, 'Подрамник подвески');
INSERT INTO `recursive` VALUES (454, 416, 'Стойка подвески в сборе');
INSERT INTO `recursive` VALUES (455, 416, 'Тяга стабилизатора подвестки');
INSERT INTO `recursive` VALUES (456, 416, 'Демферы пыльников амортизатора');
INSERT INTO `recursive` VALUES (457, 416, 'Проставки амортизатора');
INSERT INTO `recursive` VALUES (458, 416, 'Шарнир ступицы');
INSERT INTO `recursive` VALUES (460, 416, 'Стойка стабилизатора');
INSERT INTO `recursive` VALUES (461, 418, 'Подвеска');
INSERT INTO `recursive` VALUES (462, 418, 'Втулка рессоры');
INSERT INTO `recursive` VALUES (463, 418, 'Сайлентблок рычага');
INSERT INTO `recursive` VALUES (464, 418, 'Подрамник');
INSERT INTO `recursive` VALUES (465, 418, 'Рычаг');
INSERT INTO `recursive` VALUES (466, 418, 'Рычаг подвески');
INSERT INTO `recursive` VALUES (467, 418, 'Рессора');
INSERT INTO `recursive` VALUES (468, 418, 'Сайлентблок кулака');
INSERT INTO `recursive` VALUES (469, 418, 'Сайлентблок продольного рычага');
INSERT INTO `recursive` VALUES (470, 418, 'Сайлентблок подрамника');
INSERT INTO `recursive` VALUES (471, 418, 'Сайлентблок рессоры');
INSERT INTO `recursive` VALUES (472, 418, 'Шаровая опора');
INSERT INTO `recursive` VALUES (473, 418, 'Шпилька колеса');
INSERT INTO `recursive` VALUES (474, 15, 'Выхлопная система');
INSERT INTO `recursive` VALUES (475, 15, 'Катализатор');
INSERT INTO `recursive` VALUES (476, 15, 'Выпускной коллектор');
INSERT INTO `recursive` VALUES (477, 475, 'Кислородный датчик');
INSERT INTO `recursive` VALUES (478, 475, 'Катализатор');
INSERT INTO `recursive` VALUES (479, 475, 'Клапан системы рециркуляции отработанных газов');
INSERT INTO `recursive` VALUES (480, 476, 'Выпускной коллектор');
INSERT INTO `recursive` VALUES (481, 476, 'Глушитель');
INSERT INTO `recursive` VALUES (482, 476, 'Кронштейн глушителя');
INSERT INTO `recursive` VALUES (483, 476, 'Прокладка выпускного коллектора');
INSERT INTO `recursive` VALUES (484, 476, 'Прокладка глушителя');
INSERT INTO `recursive` VALUES (485, 476, 'Хомут глушителя');
INSERT INTO `recursive` VALUES (486, 476, 'Гофра глушителя');
INSERT INTO `recursive` VALUES (487, 476, 'Уплотнительное кольцо глушителя');
INSERT INTO `recursive` VALUES (488, 476, 'Опора');
INSERT INTO `recursive` VALUES (489, 476, 'Резонатор');
INSERT INTO `recursive` VALUES (490, 17, 'Ось');
INSERT INTO `recursive` VALUES (492, 17, 'Трансмиссия');
INSERT INTO `recursive` VALUES (493, 491, 'Главная передача');
INSERT INTO `recursive` VALUES (494, 491, 'Ось в сборе');
INSERT INTO `recursive` VALUES (495, 491, 'Ступица в сборе');
INSERT INTO `recursive` VALUES (496, 491, 'Поворотная ось ступицы');
INSERT INTO `recursive` VALUES (497, 491, 'Подшипник колеса');
INSERT INTO `recursive` VALUES (498, 491, 'Приводной вал');
INSERT INTO `recursive` VALUES (500, 491, 'Пыльники шарниров приводного вала');
INSERT INTO `recursive` VALUES (504, 491, 'Шарнир приводного вала');
INSERT INTO `recursive` VALUES (508, 491, 'Подшипник ступицы');
INSERT INTO `recursive` VALUES (510, 490, 'Шарнир ступицы');
INSERT INTO `recursive` VALUES (511, 490, 'Подшипник оси колеса');
INSERT INTO `recursive` VALUES (512, 490, 'Приводной вал');
INSERT INTO `recursive` VALUES (514, 490, 'Пыльники шарниров приводного вала');
INSERT INTO `recursive` VALUES (518, 490, 'Сальник приводного вала');
INSERT INTO `recursive` VALUES (520, 490, 'Шарнир приводного вала');
INSERT INTO `recursive` VALUES (524, 490, 'Подшипник ступицы');
INSERT INTO `recursive` VALUES (526, 492, 'Карданный вал');
INSERT INTO `recursive` VALUES (527, 492, 'Эластичная муфта кардана');
INSERT INTO `recursive` VALUES (528, 492, 'ШРУС');
INSERT INTO `recursive` VALUES (529, 492, 'Датчик скорости');
INSERT INTO `recursive` VALUES (530, 492, 'Крестовина карданного вала');
INSERT INTO `recursive` VALUES (531, 492, 'Подвесной подшипник');
INSERT INTO `recursive` VALUES (532, 492, 'Подшипник привода');
INSERT INTO `recursive` VALUES (533, 492, 'Полуось');
INSERT INTO `recursive` VALUES (534, 492, 'Привод');
INSERT INTO `recursive` VALUES (535, 492, 'Привод спидометра');
INSERT INTO `recursive` VALUES (536, 492, 'Пыльник ШРУСа приводного вала');
INSERT INTO `recursive` VALUES (537, 492, 'Раздатка');
INSERT INTO `recursive` VALUES (538, 492, 'Редуктор');
INSERT INTO `recursive` VALUES (539, 492, 'Сальник первичного вала');
INSERT INTO `recursive` VALUES (540, 492, 'Сальник полуоси');
INSERT INTO `recursive` VALUES (541, 492, 'Сальник привода');
INSERT INTO `recursive` VALUES (542, 492, 'Сальник редуктора');
INSERT INTO `recursive` VALUES (543, 492, 'Сальник хвостовика');
INSERT INTO `recursive` VALUES (544, 492, 'Сальник штока вывода');
INSERT INTO `recursive` VALUES (545, 492, 'Сальник сервопривода');
INSERT INTO `recursive` VALUES (547, 16, 'Аккумулятор и кабели');
INSERT INTO `recursive` VALUES (548, 16, 'Выключатель');
INSERT INTO `recursive` VALUES (549, 16, 'Генератор');
INSERT INTO `recursive` VALUES (550, 16, 'Датчик');
INSERT INTO `recursive` VALUES (551, 16, 'Лампа');
INSERT INTO `recursive` VALUES (552, 16, 'Мотор');
INSERT INTO `recursive` VALUES (553, 16, 'Предохранители и реле');
INSERT INTO `recursive` VALUES (554, 16, 'Разное');
INSERT INTO `recursive` VALUES (555, 16, 'Стартер');
INSERT INTO `recursive` VALUES (556, 16, 'Стеклоочистители и омыватели');
INSERT INTO `recursive` VALUES (557, 16, 'Фары и фонари');
INSERT INTO `recursive` VALUES (558, 547, 'Аккумуляторная батарея');
INSERT INTO `recursive` VALUES (561, 547, 'Подрулевой шлейф');
INSERT INTO `recursive` VALUES (562, 547, 'Заземляющий провод двигателя');
INSERT INTO `recursive` VALUES (563, 547, 'Заземляющий провод кузова');
INSERT INTO `recursive` VALUES (564, 547, 'Провод стартера');
INSERT INTO `recursive` VALUES (565, 547, 'Проводка');
INSERT INTO `recursive` VALUES (566, 547, 'Разъем');
INSERT INTO `recursive` VALUES (567, 547, 'Электропроводка');
INSERT INTO `recursive` VALUES (568, 548, 'Выключатель фар дальнего света');
INSERT INTO `recursive` VALUES (569, 548, 'Выключатель аварийной сигнализации');
INSERT INTO `recursive` VALUES (570, 548, 'Выключатель звукового сигнала');
INSERT INTO `recursive` VALUES (571, 548, 'Выключатель запрещения запуска');
INSERT INTO `recursive` VALUES (572, 548, 'Выключатель поворотов');
INSERT INTO `recursive` VALUES (573, 548, 'Выключатель стартера');
INSERT INTO `recursive` VALUES (574, 548, 'Выключатель омывателя');
INSERT INTO `recursive` VALUES (575, 548, 'Выключатель стоп-сигналов');
INSERT INTO `recursive` VALUES (576, 548, 'Выключатель указателя стояночного тормоза');
INSERT INTO `recursive` VALUES (577, 548, 'Выключатель фонарей заднего хода');
INSERT INTO `recursive` VALUES (578, 548, 'Переключатель света фар');
INSERT INTO `recursive` VALUES (579, 549, 'Натяжитель ремня привода генератора');
INSERT INTO `recursive` VALUES (580, 549, 'Ремень привода генератора');
INSERT INTO `recursive` VALUES (581, 549, 'Система зарядки генератора');
INSERT INTO `recursive` VALUES (582, 549, 'Выпрямитель генератора');
INSERT INTO `recursive` VALUES (583, 549, 'Шкив генератора');
INSERT INTO `recursive` VALUES (584, 549, 'Генератор');
INSERT INTO `recursive` VALUES (586, 550, 'Датчик давления турбонаддува');
INSERT INTO `recursive` VALUES (587, 550, 'Датчик положения дроссельной заслонки');
INSERT INTO `recursive` VALUES (588, 550, 'Датчик уровня топлива');
INSERT INTO `recursive` VALUES (589, 550, 'Датчик температуры охлаждающей жидкости');
INSERT INTO `recursive` VALUES (590, 550, 'Датчик остаточного кислорода');
INSERT INTO `recursive` VALUES (591, 550, 'Датчик давления шин');
INSERT INTO `recursive` VALUES (592, 550, 'Датчик давления масла');
INSERT INTO `recursive` VALUES (593, 550, 'Датчик ABS');
INSERT INTO `recursive` VALUES (594, 550, 'Датчик ГУР');
INSERT INTO `recursive` VALUES (595, 550, 'Датчик температуры окружающего воздуха');
INSERT INTO `recursive` VALUES (596, 550, 'Датчик давления хладагента АС');
INSERT INTO `recursive` VALUES (597, 550, 'Датчик заднего хода');
INSERT INTO `recursive` VALUES (598, 550, 'Датчик пневмоподвески');
INSERT INTO `recursive` VALUES (599, 550, 'Датчик работы цилиндра');
INSERT INTO `recursive` VALUES (600, 550, 'Датчик распределительного вала');
INSERT INTO `recursive` VALUES (601, 550, 'Датчик спидометра');
INSERT INTO `recursive` VALUES (602, 551, 'Лампа габарита');
INSERT INTO `recursive` VALUES (603, 551, 'Лампа подсветки номерного знака');
INSERT INTO `recursive` VALUES (604, 551, 'Лампа противотуманной фары');
INSERT INTO `recursive` VALUES (605, 551, 'Лампа указателя поворота');
INSERT INTO `recursive` VALUES (606, 551, 'Лампа ближнего света');
INSERT INTO `recursive` VALUES (607, 551, 'Лампа фонаря заднего хода');
INSERT INTO `recursive` VALUES (608, 551, 'Патрон лампы');
INSERT INTO `recursive` VALUES (609, 552, 'Блок управления стеклоподъемниками');
INSERT INTO `recursive` VALUES (610, 552, 'Двигатель омывателя');
INSERT INTO `recursive` VALUES (611, 552, 'Электродвигатель очистителя заднего стекла');
INSERT INTO `recursive` VALUES (612, 552, 'Электродвигатель очистителя лобового стекла');
INSERT INTO `recursive` VALUES (613, 552, 'Вентилятор отопителя');
INSERT INTO `recursive` VALUES (615, 552, 'Привод замка задней двери');
INSERT INTO `recursive` VALUES (616, 552, 'Привод замка передней двери');
INSERT INTO `recursive` VALUES (617, 553, 'Блок предохранителей');
INSERT INTO `recursive` VALUES (618, 553, 'Предохранитель');
INSERT INTO `recursive` VALUES (619, 553, 'Реле стеклоподъемника');
INSERT INTO `recursive` VALUES (620, 553, 'Реле поворотника');
INSERT INTO `recursive` VALUES (621, 553, 'Реле двигателя воздуходувки');
INSERT INTO `recursive` VALUES (622, 553, 'Реле насоса антиблокировочной системы тормозов');
INSERT INTO `recursive` VALUES (623, 553, 'Реле обогрева лобового стекла');
INSERT INTO `recursive` VALUES (624, 553, 'Реле обогрева заднего стекла');
INSERT INTO `recursive` VALUES (625, 553, 'Реле фар');
INSERT INTO `recursive` VALUES (626, 553, 'Реле омывателя заднего стекла');
INSERT INTO `recursive` VALUES (627, 554, 'Приборная панель');
INSERT INTO `recursive` VALUES (628, 554, 'Часы');
INSERT INTO `recursive` VALUES (629, 554, 'Электронный блок управления двигателем');
INSERT INTO `recursive` VALUES (630, 554, 'Редукционный клапан');
INSERT INTO `recursive` VALUES (631, 554, 'Звуковой сигнал');
INSERT INTO `recursive` VALUES (632, 554, 'Блок управления отопителем');
INSERT INTO `recursive` VALUES (633, 554, 'Автомагнитола');
INSERT INTO `recursive` VALUES (634, 554, 'Подрулевой переключатель');
INSERT INTO `recursive` VALUES (635, 554, 'Подушка безопасности водителя');
INSERT INTO `recursive` VALUES (636, 554, 'Подушка безопасности пассажира');
INSERT INTO `recursive` VALUES (637, 554, 'Резистор отопителя');
INSERT INTO `recursive` VALUES (638, 555, 'Стартер');
INSERT INTO `recursive` VALUES (640, 555, 'Возвратная пружина педали');
INSERT INTO `recursive` VALUES (641, 556, 'Форсунка омывателя заднего стекла');
INSERT INTO `recursive` VALUES (642, 556, 'Форсунка омывателя лобового стекла');
INSERT INTO `recursive` VALUES (643, 556, 'Бачок омывателя стекла');
INSERT INTO `recursive` VALUES (644, 557, 'Лампа подсветки багажника');
INSERT INTO `recursive` VALUES (645, 557, 'Лампа освещения салона');
INSERT INTO `recursive` VALUES (646, 557, 'Ксеноновая фара');
INSERT INTO `recursive` VALUES (647, 557, 'Блок фонарей в сборе');
INSERT INTO `recursive` VALUES (648, 557, 'Лампа бокового повторителя поворота');
INSERT INTO `recursive` VALUES (649, 557, 'Лампа отделения для перчаток');
INSERT INTO `recursive` VALUES (650, 557, 'Фара');
INSERT INTO `recursive` VALUES (651, 28, 'Диагностика');
INSERT INTO `recursive` VALUES (652, 28, 'Дополнительное оборудование');
INSERT INTO `recursive` VALUES (653, 28, 'Техническое обслуживание');
INSERT INTO `recursive` VALUES (654, 651, 'Компрессия двигателя');
INSERT INTO `recursive` VALUES (655, 651, 'Давление масла');
INSERT INTO `recursive` VALUES (656, 651, 'Зажигание');
INSERT INTO `recursive` VALUES (657, 651, 'Топливная система');
INSERT INTO `recursive` VALUES (658, 651, 'Подвеска');
INSERT INTO `recursive` VALUES (659, 651, 'Салонный фильтр');
INSERT INTO `recursive` VALUES (660, 652, 'Фаркоп');
INSERT INTO `recursive` VALUES (661, 652, 'Webasto');
INSERT INTO `recursive` VALUES (662, 652, 'Автомагнитола');
INSERT INTO `recursive` VALUES (663, 652, 'Датчик парктроника');
INSERT INTO `recursive` VALUES (664, 652, 'Динамик');
INSERT INTO `recursive` VALUES (665, 652, 'Сигнализация с автозапуском');
INSERT INTO `recursive` VALUES (666, 652, 'Брызговик');
INSERT INTO `recursive` VALUES (668, 653, 'Жидкость для омывателя стекла');
INSERT INTO `recursive` VALUES (669, 653, 'Трансмиссионное масло МКПП');
INSERT INTO `recursive` VALUES (670, 653, 'Трансмиссионное масло АКПП');
INSERT INTO `recursive` VALUES (671, 653, 'Масло в дифференциале');
INSERT INTO `recursive` VALUES (672, 653, 'Масло в муфте');
INSERT INTO `recursive` VALUES (673, 653, 'Натяжение ремня привода генератора');
INSERT INTO `recursive` VALUES (674, 653, 'Уровень жидкости');
INSERT INTO `recursive` VALUES (675, 653, 'Тормозная система');
INSERT INTO `recursive` VALUES (676, 653, 'Фара');
INSERT INTO `recursive` VALUES (677, 653, 'Сервисный интервал');
INSERT INTO `recursive` VALUES (678, 653, 'Свеча зажигания');
INSERT INTO `recursive` VALUES (679, 653, 'Дроссельная заслонка');
INSERT INTO `recursive` VALUES (680, 653, 'Охлаждающая жидкость');
INSERT INTO `recursive` VALUES (681, 653, 'Масло в редукторе');
INSERT INTO `recursive` VALUES (682, 653, 'Масло в раздаточной коробке');
INSERT INTO `recursive` VALUES (684, 653, 'Масло в усилителе руля');
INSERT INTO `recursive` VALUES (685, 653, 'Тормозная жидкость');

SET FOREIGN_KEY_CHECKS = 1;
